(define (problem sokoban2)
    (:domain sokoban)
    (:objects
        v1 v2 v3 v4 v5 v6
    )
    (:init
        (inc v1 v2)
        (inc v2 v3)
        (inc v3 v4)
        (inc v4 v5)
        (inc v5 v6)
        (dec v6 v5)
        (dec v5 v4)
        (dec v4 v3)
        (dec v3 v2)
        (dec v2 v1)
        (wall v1 v4)
        (wall v2 v1)
        (box v2 v2)
        (wall v2 v4)
        (wall v3 v1)
        (at v3 v2)
        (wall v3 v4)
        (box v4 v2)
        (box v4 v3)
        (wall v5 v4)
        (wall v6 v3)
        (wall v6 v4)
    )
    (:goal
        (and (box v1 v1) (box v1 v2) (box v1 v3))
    )
)